// This file was generated by Prisma, and assumes you have installed the following:
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "src/",
  migrations: {
    path: "src/migrations",
    seed: "tsx src/lib/seed.ts"
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
